### ISSUE TITLE
Does not toggle

### ISSUE THREAD

**Issue by mika76** [cmlewis89/vscode-togglecodelens#1]
I'm not sure why - but it does not seem to do anything for me. VSCode 1.9.1

**Comment by 31kish** [comment]
@mika76
Please delete the comment of settings.json

**Comment by mika76** [comment]
Which comment?

**Comment by 31kish** [comment]
Can't use the comment syntax with the json file.

ForExample:

settings.json
```json
// Place your settings in  this file to overwrite the default settings
{
  "editor.lineNumbers": "off"
}
```

**Comment by adenflorian** [comment]
Doesn't work for me either, 1.11.1

@31kish I don't understand...

**Comment by NinoFloris** [comment]
Does nothing, also not if I remove all comments from user and workspace settings.json  

ahh ...

Hardcoded to normal vscode, why not use the workspace settings file for this? No need to do OS based path detection either 
```
            case EnvironemtType.Mac:
                return process.env.HOME + '/Library/Application Support/Code/User/settings.json';
```

**Comment by NinoFloris** [comment]
ahh ...

Hardcoded to normal vscode, why not use the workspace settings file for this? No need to do OS based path detection either 
```
            case EnvironemtType.Mac:
                return process.env.HOME + '/Library/Application Support/Code/User/settings.json';
```

**Comment by NinoFloris** [comment]
@cmlewis89 Would you accept a pull request that changes this plugin to use the workspace settings.json file? ($WorkspaceRoot/.vscode/settings.json)

**Comment by ghost** [comment]
It does not seem to do anything in vscode 1.23.1 either

**Comment by ho-wan** [comment]
I wanted an easier way to toggle codelens but this extension doesn't work for me either. Therefore I made my own extension called "Setting Toggle". It also comes with a button, and you can also bind it to toggle any custom setting.
[Setting Toggle](https://marketplace.visualstudio.com/items?itemName=Ho-Wan.setting-toggle)
(Apologies for crashing this thread.)

**Comment by mika76** [comment]
thanks @Ho-Wan it seems like his project is dead anyway
